create SCHEMA ALIENGAMESCHEMA;

drop TABLE ALIENGAMESCHEMA.RECORDS;

create TABLE ALIENGAMESCHEMA.RECORDS(name VARCHAR(20), winTime INTEGER);

insert into ALIENGAMESCHEMA.RECORDS values ('Abraham', 100000);

select * from ALIENGAMESCHEMA.RECORDS;

