package com.asc.game.model;

// Generated Feb 22, 2013 8:49:54 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Records generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "RECORDS", schema = "ALIENGAMESCHEMA")
public class Records implements java.io.Serializable {

	private RecordsId id;

	public Records() {
	}

	public Records(RecordsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "name", column = @Column(name = "NAME", length = 20)),
			@AttributeOverride(name = "wintime", column = @Column(name = "WINTIME")) })
	public RecordsId getId() {
		return this.id;
	}

	public void setId(RecordsId id) {
		this.id = id;
	}

}
